# Generated by Django 5.0.4 on 2024-04-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPyTrack',
            fields=[
                ('Pk', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Task', models.CharField(blank=True, max_length=255)),
                ('Slug', models.CharField(blank=True, max_length=255)),
                ('Description', models.TextField(blank=True)),
                ('Init_Date', models.CharField(blank=True, max_length=10)),
                ('Complete_Date', models.CharField(blank=True, max_length=10)),
                ('Deadline_Date', models.CharField(blank=True, max_length=10)),
                ('File', models.FileField(blank=True, upload_to='<django.db.models.fields.BigAutoField>-<django.db.models.fields.CharField>')),
                ('Priority', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Emergency'), (2, 'High'), (3, 'Medium'), (4, 'Low')], null=True)),
                ('Note', models.TextField(blank=True)),
                ('Is_Complete', models.BooleanField(default=False)),
            ],
        ),
    ]
