# Generated by Django 5.0.4 on 2024-04-11 12:02

import Tracker.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.CharField(blank=True, max_length=255)),
                ('Slug', models.CharField(blank=True, max_length=255)),
                ('Description', models.TextField(blank=True)),
                ('Init_Date', models.CharField(blank=True, max_length=10)),
                ('Deadline_Date', models.CharField(blank=True, max_length=10)),
                ('Priority', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Emergency'), (2, 'High'), (3, 'Medium'), (4, 'Low')], null=True)),
                ('Is_Complete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(blank=True, upload_to=Tracker.models.create_with_pk)),
                ('Complete_Date', models.CharField(blank=True, max_length=10)),
                ('Note', models.TextField(blank=True)),
                ('Checklist', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Tracker.task')),
            ],
            options={
                'verbose_name_plural': 'Tracks',
            },
        ),
    ]
