# Generated by Django 5.0.4 on 2024-04-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_remove_taskpytrack_pk_taskpytrack_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskpytrack',
            options={'verbose_name_plural': 'Task'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='taskpytrack',
            order_with_respect_to='Priority',
        ),
    ]
