# Generated by Django 5.0.4 on 2024-04-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_alter_taskpytrack_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskpytrack',
            options={'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='taskpytrack',
            order_with_respect_to=None,
        ),
    ]
