# Generated by Django 5.0.4 on 2024-04-09 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0005_task_track_delete_taskpytrack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='Task',
            new_name='Checklist',
        ),
    ]
